spring:
  application:
    name: legion-gateway
  profiles:
    include:
      - tags

# server
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  servlet:
    context-path: /gateway

# management
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info

# logging
logging:
  path: logs
  level:
    org.springframework: info
    com.zcs.legion.gateway: debug
    com.legion.client: debug
    com.legion.net: debug

#legion config
legion:
  net:
    serverUrls:
      - tcp://127.0.0.1:8849
    node:
      nodeId: legion-gateway
      groupId: legion-gateway
