spring:
  application:
    name: legion-gateway

# server
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  servlet:
    context-path: /gateway

# management
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info

# logging
logging:
  path: logs
  level:
    org.springframework: info
    com.zcs.legion.gateway: debug
