spring:
  application:
    name: zcs-legion-gateway
  profiles:
    include: tags

# server
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000
  servlet:
    context-path: /

# management
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /exporter
      exposure:
        include: prometheus
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 1${server.port}

# logging
logging:
  path: logs
  level:
    org.springframework: info
    com.zcs.legion.gateway: info
    com.legion: info

#legion config
legion:
  net:
    serverUrls:
      - tcp://127.0.0.1:8850
    node:
      nodeId: legion-gateway
      groupId: legion-gateway
